#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Alex de Oliveira Souza'
        hostname: ubuntu-px
        username: alex
        password: '$y$j9T$pwURDa/CTwScXwLa1Txp2/$xS7Ahkh8dec5qEAUWjfrXnUH75tg5XoV2KwGAeslGU3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
    	- git
	- wget
	- htop
 	- btop
	- curl
	- git
 	- flatpak
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
        
